#include <iostream>
#include <memory>
#include <string>

#include <grpcpp/grpcpp.h>
#include "src/proto/greeter.grpc.pb.h" // Generated by Bazel!

using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using greeter::Greeter;
using greeter::HelloRequest;
using greeter::HelloReply;

class GreeterServiceImpl final : public Greeter::Service {
    grpc::Status SayHello(ServerContext* context, const HelloRequest* request,
                          HelloReply* reply) override {
        std::string prefix("Hello from C++ Server, ");
        reply->set_message(prefix + request->name());
        return grpc::Status::OK;
    }
};

void RunServer() {
    std::string server_address("0.0.0.0:50051");
    GreeterServiceImpl service;

    ServerBuilder builder;
    builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
    builder.RegisterService(&service);
    std::unique_ptr<Server> server(builder.BuildAndStart());
    std::cout << "Server listening on " << server_address << std::endl;
    server->Wait();
}

int main() {
    RunServer();
    return 0;
}